import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Dummy from "@/components/Dummy";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, hunting blog, hunting coder" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <nav className={styles.mainnav}>
          <ul>
            <Link href="/">
              <li>Home</li>
            </Link>
            <Link href="/blog">
              <li>Blog</li>
            </Link>
            <Link href="/about">
              <li>About</li>
            </Link>
            <Link href="/contact">
              <li>Contact</li>
            </Link>
          </ul>
        </nav>
        <main className={styles.main}>
          <Dummy />
          <style jsx>
            {`
              .mySpan {
                color: blue;
              }
            `}
          </style>
          <h1>
            <span className="mySpan dummy">Hunting Coder</span>
          </h1>
          <p>A blog for hunting coders by a hunting coder</p>
          <div className={styles.blogs}>
            <h2>Popular Blogs</h2>
            <div className={styles.blogItem}>
              <h3>how to learn javascript in 2024</h3>
              <p>JavaScript is a language used to design logic for the web</p>
            </div>
            <div className={styles.blogItem}>
              <h3>how to learn javascript in 2024</h3>
              <p>JavaScript is a language used to design logic for the web</p>
            </div>
            <div className={styles.blogItem}>
              <h3>how to learn javascript in 2024</h3>
              <p>JavaScript is a language used to design logic for the web</p>
            </div>
            <div className={styles.blogItem}>
              <h3>how to learn javascript in 2024</h3>
              <p>JavaScript is a language used to design logic for the web</p>
            </div>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
      </div>
    </>
  );
}
